BB-116: create service users with an assigned role+policy to assume

diff --git a/bin/ensureServiceUser b/bin/ensureServiceUser
--- a/bin/ensureServiceUser
+++ b/bin/ensureServiceUser
@@ -3,30 +3,55 @@
 // TODO
 // - deduplicate with Vault's seed script at https://github.com/scality/Vault/pull/1627
 // - add permission boundaries to user when https://scality.atlassian.net/browse/VAULT-4 is implemented
+const fs = require('fs');
 
-const { errors } = require('arsenal');
+const { errors, errorUtils } = require('arsenal');
 const program = require('commander');
 const werelogs = require('werelogs');
 const version = require('../package.json').version;
 const async = require('async');
-const { IAM } = require('aws-sdk');
+const { IAM, STS } = require('aws-sdk');
 
 const systemPrefix = '/scality-internal/';
 
-function generateUserPolicyDocument(roleName) {
+function generateUserAssumeRolePolicyDocument(roleName, targetAccount) {
     return {
-        "Version": "2012-10-17",
-        "Statement": {
-            "Effect": "Allow",
-            "Action": "sts:AssumeRole",
-            "Resource": `arn:aws:iam::*:role${systemPrefix}${roleName}`,
+        Version: '2012-10-17',
+        Statement: {
+            Effect: 'Allow',
+            Action: 'sts:AssumeRole',
+            Resource: `arn:aws:iam::${targetAccount}:role${systemPrefix}${roleName}`,
         }
     };
+}
+
+function generateRoleTrustPolicyDocument(userArn) {
+    return {
+        Version: '2012-10-17',
+        Statement: [
+          {
+            Effect: 'Allow',
+            Principal: {
+              AWS: userArn,
+            },
+            Action: 'sts:AssumeRole',
+            Condition: {}
+          }
+        ]
+     };
 }
 
 function createIAMClient(opts) {
     return new IAM({
         endpoint: opts.iamEndpoint,
+        region: opts.region,
+    });
+}
+
+function createSTSClient(opts) {
+    return new STS({
+        endpoint: opts.stsEndpoint,
+        region: opts.region,
     });
 }
 
@@ -39,34 +64,44 @@ function needsCreation(v) {
 }
 
 class BaseHandler {
-    constructor(serviceName, iamClient, log) {
+    constructor(serviceName, iamClient, log, options) {
         this.serviceName = serviceName;
         this.iamClient = iamClient;
         this.log = log;
+        this.options = options || {};
+        this.name = this.options.name;
+        this.resourceTypeSuffix = this.name ? `_${this.name}` : '';
+        this.resourceNameSuffix = this.name ? `-${this.name}` : '';
+        this.resourceName = `${this.serviceName}${this.resourceNameSuffix}`;
+        this.stsClient = this.options.stsClient;
+    }
+
+    get fqResourceType() {
+        return `${this.resourceType}${this.resourceTypeSuffix}`;
     }
 
     applyWaterfall(values, done) {
-        this.log.debug('applyWaterfall', { values, type: this.resourceType });
+        this.log.debug('applyWaterfall', { values, type: this.fqResourceType });
 
-        const v = values[this.resourceType];
+        const v = values[this.fqResourceType];
 
         if (needsCreation(v)) {
-            this.log.debug('creating', { v, type: this.resourceType });
+            this.log.debug('creating', { v, type: this.fqResourceType });
             return this.create(values)
                 .then(res =>
                     done(null, Object.assign(values, {
-                        [this.resourceType]: res,
+                        [this.fqResourceType]: res,
                     })))
                 .catch(done);
         }
 
-        this.log.debug('conflicts check', { v, type: this.resourceType });
+        this.log.debug('conflicts check', { v, type: this.fqResourceType });
         if (this.conflicts(v)) {
             return done(errors.EntityAlreadyExists.customizeDescription(
-                `${this.resourceType} ${this.serviceName} already exists and conflicts with the expected value.`));
+                `${this.fqResourceType} ${this.serviceName} already exists and conflicts with the expected value.`));
         }
 
-        this.log.debug('nothing to do', { v, type: this.resourceType });
+        this.log.debug('nothing to do', { v, type: this.fqResourceType });
         return done(null, values);
     }
 }
@@ -78,7 +113,7 @@ class UserHandler extends BaseHandler {
 
     collect() {
         return this.iamClient.getUser({
-            UserName: this.serviceName,
+            UserName: this.resourceName,
         })
         .promise()
         .then(res => res.User);
@@ -86,7 +121,7 @@ class UserHandler extends BaseHandler {
 
     create(allResources) {
         return this.iamClient.createUser({
-            UserName: this.serviceName,
+            UserName: this.resourceName,
             Path: systemPrefix,
         })
         .promise()
@@ -94,7 +129,7 @@ class UserHandler extends BaseHandler {
     }
 
     conflicts(u) {
-        return u.Path !== systemPrefix;        
+        return u.Path !== systemPrefix;
     }
 }
 
@@ -110,18 +145,38 @@ class PolicyHandler extends BaseHandler {
             Scope: 'All',
         })
         .promise()
-        .then(res => res.Policies.find(p => p.PolicyName === this.serviceName));
+        .then(res => res.Policies.find(p => p.PolicyName === this.resourceName));
     }
 
     create(allResources) {
-        const doc = generateUserPolicyDocument(this.serviceName);
+        return new Promise((resolve, reject) => {
+            if (!this.options.constrainToThisAccount) {
+                return resolve('*');
+            }
 
-        return this.iamClient.createPolicy({
-            PolicyName: this.serviceName,
-            PolicyDocument: JSON.stringify(doc),
-            Path: systemPrefix,
+            return this.stsClient.getCallerIdentity((err, res) => {
+                if (err) {
+                    return reject(err);
+                }
+
+                return resolve(res.Account);
+            });
         })
-        .promise()
+        .then(accountId => {
+            if (this.options.policy) {
+                return this.options.policy;
+            }
+
+            return generateUserAssumeRolePolicyDocument(this.serviceName, accountId);
+        })
+        .then(policyDocument =>
+            this.iamClient.createPolicy({
+                PolicyName: this.resourceName,
+                PolicyDocument: JSON.stringify(policyDocument),
+                Path: systemPrefix,
+            })
+            .promise()
+        )
         .then(res => res.Policy);
     }
 
@@ -130,24 +185,82 @@ class PolicyHandler extends BaseHandler {
     }
 }
 
-class PolicyAttachmentHandler extends BaseHandler {
+class RoleHandler extends BaseHandler {
+    get resourceType() {
+        return 'role';
+    }
+
+    collect() {
+        return this.iamClient.getRole({
+            RoleName: this.resourceName,
+        })
+        .promise()
+        .then(res => res.Role);
+    }
+
+    create(allResources) {
+        const trustPolicy = generateRoleTrustPolicyDocument(allResources.user.Arn);
+
+        return this.iamClient.createRole({
+            RoleName: this.resourceName,
+            Path: systemPrefix,
+            AssumeRolePolicyDocument: JSON.stringify(trustPolicy),
+        })
+        .promise()
+        .then(res => res.Role);
+    }
+
+    conflicts(p) {
+        return p.Path !== systemPrefix;
+    }
+}
+
+class PolicyUserAttachmentHandler extends BaseHandler {
     get resourceType() {
         return 'policyAttachment';
     }
 
     collect() {
         return this.iamClient.listAttachedUserPolicies({
-            UserName: this.serviceName,
+            UserName: this.resourceName,
             MaxItems: 100,
         })
         .promise()
-        .then(res => res.AttachedPolicies)
+        .then(res => res.AttachedPolicies);
     }
 
     create(allResources) {
+        console.log('***', allResources);
         return this.iamClient.attachUserPolicy({
-            PolicyArn: allResources.policy.Arn,
-            UserName: this.serviceName,
+            PolicyArn: allResources.policy_user.Arn,
+            UserName: this.resourceName,
+        })
+        .promise();
+    }
+
+    conflicts(p) {
+        return false;
+    }
+}
+
+class PolicyRoleAttachmentHandler extends BaseHandler {
+    get resourceType() {
+        return 'policyRoleAttachment';
+    }
+
+    collect() {
+        return this.iamClient.listAttachedRolePolicies({
+            RoleName: this.resourceName,
+            MaxItems: 100,
+        })
+        .promise()
+        .then(res => res.AttachedPolicies);
+    }
+
+    create(allResources) {
+        return this.iamClient.attachRolePolicy({
+            PolicyArn: allResources.policy_role.Arn,
+            RoleName: this.resourceName,
         })
         .promise();
     }
@@ -164,16 +277,16 @@ class AccessKeyHandler extends BaseHandler {
 
     collect() {
         return this.iamClient.listAccessKeys({
-            UserName: this.serviceName,
+            UserName: this.resourceName,
             MaxItems: 100,
         })
         .promise()
-        .then(res => res.AccessKeyMetadata)
+        .then(res => res.AccessKeyMetadata);
     }
 
     create(allResources) {
         return this.iamClient.createAccessKey({
-            UserName: this.serviceName,
+            UserName: this.resourceName,
         })
         .promise()
         .then(res => res.AccessKey);
@@ -191,30 +304,62 @@ function collectResource(v, done) {
             if (err.code === 'NoSuchEntity') {
                 return done(null, null);
             }
-
+console.log('&&&&&&&&&', v, err);
             done(err);
         });
 }
 
 function collectResourcesFromHandlers(handlers, cb) {
     const tasks = handlers.reduce((acc, v) => ({
-        [v.resourceType]: done => collectResource(v, done),
+        [v.fqResourceType]: done => collectResource(v, done),
         ...acc,
     }), {});
     async.parallel(tasks, cb);
 }
 
-function buildServiceUserHandlers(serviceName, client, log) {
+function buildServiceUserForCrossAccountAssumeRoleHandlers(serviceName, client, log) {
     return [
-        UserHandler,
-        PolicyHandler,
-        PolicyAttachmentHandler,
-        AccessKeyHandler,
-    ].map(h => new h(serviceName, client, log));
+        new UserHandler(serviceName, client, log),
+        new PolicyHandler(serviceName, client, log, {
+            name: 'user',
+            policy: generateUserAssumeRolePolicyDocument(serviceName),
+        }),
+        new PolicyUserAttachmentHandler(serviceName, client, log),
+        new AccessKeyHandler(serviceName, client, log),
+    ];
 }
 
-function apply(client, serviceName, log, cb) {
-    const handlers = buildServiceUserHandlers(serviceName, client, log);
+function buildServiceUserForInAccountAssumeRoleHandlers(serviceName, policy, iamClient, stsClient, log) {
+    return [
+        // try permission policy first so that the waterfall
+        // fails early if it contains forbidden actions
+        new PolicyHandler(serviceName, iamClient, log, {
+            policy,
+            name: 'role',
+        }),
+        new UserHandler(serviceName, iamClient, log),
+        new PolicyHandler(serviceName, iamClient, log, {
+            stsClient,
+            name: 'user',
+            constrainToThisAccount: true,
+        }),
+        new PolicyUserAttachmentHandler(serviceName, iamClient, log),
+        new RoleHandler(serviceName, iamClient, log),
+        new PolicyRoleAttachmentHandler(serviceName, iamClient, log),
+        new AccessKeyHandler(serviceName, iamClient, log),
+    ];
+}
+
+function apply(iamClient, stsClient, serviceName, policyFile, log, cb) {
+    let handlers;
+
+    if (policyFile) {
+        const policyStr = fs.readFileSync(policyFile);
+        const policy = JSON.parse(policyStr);
+        handlers = buildServiceUserForInAccountAssumeRoleHandlers(serviceName, policy, iamClient, stsClient, log);
+    } else {
+        handlers = buildServiceUserForCrossAccountAssumeRoleHandlers(serviceName, iamClient, log);
+    }
 
     async.waterfall([
         done => collectResourcesFromHandlers(handlers, done),
@@ -225,44 +370,45 @@ function apply(client, serviceName, log, cb) {
 
 function wrapAction(actionFunc, serviceName, options) {
     werelogs.configure({
-        level: options.logLevel,
-        dump: options.logDumpLevel,
+        level: options.parent.logLevel,
+        dump: options.parent.logDumpLevel,
     });
 
     const log = new werelogs.Logger(process.argv[1]).newRequestLogger();
-    const client = createIAMClient(options);
+    const iamClient = createIAMClient(options.parent);
+    const stsClient = createSTSClient(options.parent);
 
-    actionFunc(client, serviceName, log, (err, data) => {
+    actionFunc(iamClient, stsClient, serviceName, options.policy, log, (err, data) => {
         if (err) {
             log.error('failed', {
                 data,
-                error: err,
+                error: errorUtils.reshapeExceptionError(err),
             });
             if (err.EntityAlreadyExists) {
                 log.error(`run "${process.argv[1]} purge ${serviceName}" to fix.`);
             }
             process.exit(1);
         }
-        log.info("success", { data });
+        log.info('success', { data });
         process.exit();
     });
 }
 
 program.version(version);
 
-[
-    {
-        name: 'apply <service-name>',
-        actionFunc: apply,
-    },
-].forEach(cmd => {
-    program
-        .command(cmd.name)
-        .option('--iam-endpoint <url>', 'IAM endpoint', 'http://localhost:8600')
-        .option('--log-level <level>', 'log level', 'info')
-        .option('--log-dump-level <level>', 'log level that triggers a dump of the debug buffer', 'error')
-        .action(wrapAction.bind(null, cmd.actionFunc));
-});
+program
+    .option('--iam-endpoint <url>', 'IAM endpoint', 'http://localhost:8600')
+    .option('--sts-endpoint <url>', 'STS endpoint', 'http://localhost:8800')
+    .option('--region <region>', 'AWS region', 'us-east-1')
+    .option('--log-level <level>', 'log level', 'info')
+    .option('--log-dump-level <level>', 'log level that triggers a dump of the debug buffer', 'error');
+
+program
+    .command('apply <service-name>')
+    .option('-p, --policy <policy-file.json>', 'Create a policy using the provided document' +
+        ' and attach it to a role that the service user is allowed to assume, instead' +
+        ' of only allowing the user to assume one (seeded) role named <service-name> in all accounts.')
+    .action(wrapAction.bind(null, apply));
 
 const validCommands = program.commands.map(n => n._name);
 
