ZENKO-2239 now uploading backbeat docker image to registry.scality.com

diff --git a/eve/main.yml b/eve/main.yml
--- a/eve/main.yml
+++ b/eve/main.yml
@@ -9,16 +9,37 @@ branches:
 
 
 models:
-  - SetProperty: &docker_image_name
-      name: Set docker image name property
-      property: docker_image_name
-      value:
-        "%(secret:private_registry_url)s/zenko/backbeat:\
-        %(prop:commit_short_revision)s"
+  - SetProperty: &registry_url
+      name: registry
+      property: registry_url
+      value: registry.scality.com/zenko-dev/backbeat
+  - SetProperty: &docker_tag_revision
+      name: Set docker tag revision property
+      property: docker_tag_revision
+      value: "%(prop:registry_url)s:%(prop:commit_short_revision)s"
+  - SetProperty: &docker_tag_latest
+      name: Set docker tag latest property
+      property: docker_tag_latest
+      value: "%(prop:registry_url)s:latest-%(prop:product_version)s"
   - ShellCommand: &docker_build
       name: Build docker image
       command: >-
-        docker build -t %(prop:docker_image_name)s .
+        docker build
+        -t %(prop:docker_tag_revision)s
+        -t %(prop:docker_tag_latest)s
+        .
+  - ShellCommand: &wait_docker_daemon
+      name: Wait for Docker daemon to be ready
+      command: |
+        bash -c '
+        for i in {1..150}
+        do
+          docker info &> /dev/null && exit
+          sleep 2
+        done
+        echo "Could not reach Docker daemon from buildbot worker" >&2
+        exit 1'
+      haltOnFailure: true
 
 stages:
   pre-merge:
@@ -106,22 +127,30 @@ stages:
         release: eve/workers/release
     steps:
       - Git: *git
-      - SetProperty: *docker_image_name
+      - ShellCommand: *wait_docker_daemon
+      - SetProperty: *registry_url
+      - SetProperty: *docker_tag_revision
+      - SetProperty: *docker_tag_latest
       - ShellCommand: *docker_build
 
   post-merge:
     worker: *image_builder
     steps:
       - Git: *git
+      - ShellCommand: *wait_docker_daemon
       - ShellCommand: &docker_login
           name: Private Registry Login
           command: >
             docker login
-            -u '%(secret:private_registry_username)s'
-            -p '%(secret:private_registry_password)s'
-            '%(secret:private_registry_url)s'
-      - SetProperty: *docker_image_name
+            -u '%(secret:harbor_login)s'
+            -p '%(secret:harbor_password)s'
+            registry.scality.com
+      - SetProperty: *registry_url
+      - SetProperty: *docker_tag_revision
+      - SetProperty: *docker_tag_latest
       - ShellCommand: *docker_build
       - ShellCommand: &docker_push
-          name: Push image
-          command: docker push %(prop:docker_image_name)s
+          name: Push images
+          command: |
+            docker push %(prop:docker_tag_revision)s
+            docker push %(prop:docker_tag_latest)s
